daily_update_service:
  image: abhijitsarkar/docker:daily-update-service
  ports:
    - 10000:10000
    - 12000:12000
  environment:
    DISCOVERY_HOST: 192.168.99.107
    DISCOVERY_PORT: 8761
    CONFIG_HOST: 192.168.99.107
    CONFIG_PORT: 8888
    DAILY_UPDATE_HOST: 192.168.99.107
    HTTP_PORT: 10000
    DEBUG_PORT: 12000
movie_service:
  image: abhijitsarkar/docker:movie-service
  ports:
    - 9000:9000
  environment:
    DISCOVERY_HOST: 192.168.99.107
    DISCOVERY_PORT: 8761
    CONFIG_HOST: 192.168.99.107
    CONFIG_PORT: 8888
    MOVIE_HOST: 192.168.99.107
    HTTP_PORT: 9000
discovery:
  image: abhijitsarkar/java-ee:discovery-service
  ports:
    - 8761:8761
  environment:
    DISCOVERY_HOST: 192.168.99.107
    HTTP_PORT: 8761
config:
  image: abhijitsarkar/java-ee:config-service
  ports:
      - 8888:8888
  environment:
    SPRING_PROFILES_ACTIVE: native
    CONFIG_LOCATION: "file:/etc/daily-update-service/config/"
    DISCOVERY_HOST: 192.168.99.107
    DISCOVERY_PORT: 8761
    CONFIG_HOST: 192.168.99.107
    HTTP_PORT: 8888
  volumes:
      - "../config/:/etc/daily-update-service/config/"